services:
  - type: web
    name: exam-portal
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        value: "postgresql://exam_portal_db_8ssq_user:BHePNhr8ZgKjNXPsXvbzvQPeWzCc4iMj@dpg-d780cs94bi0s73f7hgl0-a/exam_portal_db_8ssq"
