# Generated by Django 6.0.3 on 2026-04-03 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
